services:
  directus:
    image: directus/directus:11.10.2
    ports:
      - 8055:8055
    volumes:
      - directus_data:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    env_file:
    - .env

volumes:
  directus_data: